import Modal from "../popupBasic/Modal";
import './RestaurantMenu.css';
import { AiOutlineClose } from "react-icons/ai";
import { BsPlayFill } from "react-icons/bs";

function RestaurantMenu({
  open,
  close
}) {
    return (
      <Modal
      open={open}
     >
       <div>Menu Restauracji</div><AiOutlineClose onClick={close} id="cross"/>
       <div>
          <div>
            Przystawki:
            <div>
              <BsPlayFill/> 
              <div>
                danie
              </div>
              <div>cena</div>
            </div>
            <div>
              <BsPlayFill/> 
              <div>
                danie
              </div>
              <div>cena</div>
            </div>
            <div>
              <BsPlayFill/> 
              <div>
                danie
              </div>
              <div>cena</div>
            </div>
          </div>   
          <div>
            Zupy:
            <div>
              <BsPlayFill/> 
              <div>
                danie
              </div>
              <div>cena</div>
            </div>
            <div>
              <BsPlayFill/> 
              <div>
                danie
              </div>
              <div>cena</div>
            </div>
            <div>
              <BsPlayFill/> 
              <div>
                danie
              </div>
              <div>cena</div>
            </div>
          </div>
       </div>
       <div>
          <div>
            Dania główne:
            <div>
              <BsPlayFill/> 
              <div>
                danie
              </div>
              <div>cena</div>
            </div>
            <div>
              <BsPlayFill/> 
              <div>
                danie
              </div>
              <div>cena</div>
            </div>
            <div>
              <BsPlayFill/> 
              <div>
                danie
              </div>
              <div>cena</div>
            </div>
          </div>  
          <div>
            Desery:
            <div>
              <BsPlayFill/> 
              <div>
                danie
              </div>
              <div>cena</div>
            </div>
            <div>
              <BsPlayFill/> 
              <div>
                danie
              </div>
              <div>cena</div>
            </div>
            <div>
              <BsPlayFill/> 
              <div>
                danie
              </div>
              <div>cena</div>
            </div>
          </div>
       </div>
       <div>
         Napoje:
          <div>
            bezalkoholowe
            <div>
              <BsPlayFill/> 
              <div>
                danie
              </div>
              <div>cena</div>
            </div>
            <div>
              <BsPlayFill/> 
              <div>
                danie
              </div>
              <div>cena</div>
            </div>
            <div>
              <BsPlayFill/> 
              <div>
                danie
              </div>
              <div>cena</div>
            </div>
          </div>  
          <div>
            alkoholowe
            <div>
              <BsPlayFill/> 
              <div>
                danie
              </div>
              <div>cena</div>
            </div>
            <div>
              <BsPlayFill/> 
              <div>
                danie
              </div>
              <div>cena</div>
            </div>
            <div>
              <BsPlayFill/> 
              <div>
                danie
              </div>
              <div>cena</div>
            </div>
          </div>
       </div>
       
    </Modal>
  );
}

export default RestaurantMenu;
